version: "3"

volumes:
  postgres_data_patio:
    driver: local

services:

  db:
    image: postgres:10
    environment:
      POSTGRES_DB: patio
      POSTGRES_USER: patio
      POSTGRES_PASSWORD: patio
    volumes:
      - postgres_data_patio:/var/lib/postgresql/data

  api:
    build: ./patio-api
    depends_on:
      - db
    environment:
      PATIO_HOST:  localhost
      # DATABASE
      PATIO_JDBC_URL: jdbc:postgresql://db:5432/patio
      PATIO_JDBC_USER: patio
      PATIO_JDBC_PASSWORD: patio
      PATIO_JDBC_DRIVER: org.postgresql.Driver
      # AWS MAIL
      PATIO_AWS_EMAIL_ENABLED: "true"
      PATIO_AWS_EMAIL_REGION: region
      PATIO_AWS_EMAIL_SOURCE: email_source
      PATIO_AWS_ACCESS_KEY: access_key
      PATIO_AWS_SECRET_KEY: secret_key
      # DEFAULT USER
      PATIO_DUSER_ENABLED: "true"
      PATIO_DUSER_NAME: hello
      PATIO_DUSER_EMAIL: hello@email.com
      PATIO_DUSER_PASSWORD: password
      # JWT AUTHENTICATION
      PATIO_JWT_SECRET: mysupersecret
      PATIO_JWT_ALGO: HS256
      PATIO_JWT_ISSUER: patio
      PATIO_JWT_DAYS: 7
      # OAUTH
      PATIO_OAUTH2_KEY: oauth_2_key
      PATIO_OAUTH2_SECRET: oauth_2_secret
      PATIO_OAUTH2_CALLBACK: oauth_2_callback

  front:
    build:
      context: ./patio-front
      args:
        VUE_APP_API_URL: graphql
        VUE_APP_OAUTH2_CLIENT_ID: oauth2_client_id
        VUE_APP_TOKEN_URI: token_uri
        VUE_APP_AUTH_URI: auth_uri
        VUE_APP_SCOPE: 'email'
    depends_on:
      - api
    ports:
      - 20000:80
